Repository powerapi-ng/powerapi, pull requests merged in 2019-05, with the labels that each got.

#37 fix: Add fix for pusher_actors with type hint
  powerapi/formula/dummy/dummy_formula_actor.py
  powerapi/formula/formula_actor.py
Labels: bug, enhancement

#39 Docker image building optimizations
  .dockerignore
  .gitignore
  Dockerfile
Labels: enhancement

#43 Delete Model from Formula
  powerapi/formula/__init__.py
  powerapi/formula/dummy/dummy_formula_actor.py
  powerapi/formula/dummy/dummy_handlers.py
  powerapi/formula/dummy/dummy_model.py
  powerapi/formula/formula_actor.py
  powerapi/handler/__init__.py
  powerapi/model/__init__.py
  powerapi/model/model.py
Labels: bug

#45 State with actor attribute and some refactoring
  powerapi/actor/actor.py
  powerapi/actor/state.py
  powerapi/dispatcher/dispatcher_actor.py
  powerapi/dispatcher/handlers.py
  powerapi/dispatcher/state.py
  powerapi/formula/dummy/dummy_formula_actor.py
  powerapi/formula/dummy/dummy_handlers.py
  powerapi/formula/formula_actor.py
  powerapi/handler/handler.py
  powerapi/handler/poison_pill_message_handler.py
  powerapi/handler/start_handler.py
  powerapi/puller/handlers.py
  powerapi/puller/puller_actor.py
  powerapi/pusher/handlers.py
  powerapi/pusher/pusher_actor.py
  tests/integration/dispatcher/fake_formula.py
  tests/integration/dispatcher/test_integration_dispatcher.py
  tests/integration/puller/fake_dispatcher.py
  tests/integration/puller/test_integration_puller.py
  tests/integration/puller/test_integration_puller_actor.py
  tests/unit/actor/test_actor.py
  tests/unit/actor/test_supervisor.py
  tests/unit/dispatcher/test_dispatcher_actor.py
  tests/unit/puller/test_puller_actor.py
  tests/unit/pusher/test_pusher_actor.py
Labels: bug, enhancement

#50 Autodoc with typehint
  docs/source/conf.py
  powerapi/report_model/hwpc_model.py
  powerapi/report_model/power_model.py
  powerapi/report_model/report_model.py
  setup.cfg
Labels: doc, enhancement
