Repository powerapi-ng/powerapi, pull requests merged in 2024-05, with the labels that each got.

#331 refactor: Fix pylint warnings
  src/powerapi/actor/socket_interface.py
  src/powerapi/pusher/handlers.py
Labels: refactoring

#343 docs: Add CITATION.cff file
  CITATION.cff
Labels: doc

#344 fix(report): Fix `PowerReport` tags filtering
  src/powerapi/database/prometheus_db.py
  src/powerapi/report/power_report.py
  tests/unit/report/conftest.py
  tests/unit/report/test_power_report.py
Labels: bug, consortium
