Repository powerapi-ng/powerapi, pull requests merged in 2024-04, with the labels that each got.

#294 build: Bump minimal Python version to 3.10
  .github/workflows/build.yml
  pyproject.toml
Labels: enhancement

#296 refactor: Clean `utils` module
  src/powerapi/cli/config_parser.py
  src/powerapi/cli/parsing_manager.py
  src/powerapi/dispatcher/__init__.py
  src/powerapi/dispatcher/dispatcher_actor.py
  src/powerapi/dispatcher/handlers.py
  src/powerapi/utils/__init__.py
  src/powerapi/utils/cli.py
  src/powerapi/utils/tree.py
  tests/unit/dispatcher/test_dispatcher_actor.py
  tests/unit/utils/test_tree.py
  tests/utils/formula/dummy/dummy_handlers.py
Labels: refactoring

#297 fix(actor): Memory usage problem with slow actors
  src/powerapi/actor/socket_interface.py
Labels: bug

#302 feat(dispatcher): Optimize dispatcher routing table
  src/powerapi/dispatcher/route_table.py
  tests/unit/dispatcher/test_dispatcher_actor.py
Labels: enhancement

#303 feat(actor): Optimize actor handler
  src/powerapi/actor/actor.py
  src/powerapi/actor/state.py
  tests/unit/actor/abstract_test_actor.py
Labels: enhancement

#306 feat(database): Add `disconnect` method
  src/powerapi/database/base_db.py
  src/powerapi/database/csvdb.py
  src/powerapi/database/file_db.py
  src/powerapi/database/influxdb2.py
  src/powerapi/database/mongodb.py
  src/powerapi/database/opentsdb.py
  src/powerapi/database/prometheus_db.py
  src/powerapi/database/socket_db.py
  src/powerapi/database/virtiofs_db.py
  src/powerapi/puller/handlers.py
  src/powerapi/puller/puller_actor.py
  tests/utils/db/db.py
Labels: enhancement

#307 fix(puller): Set database puller thread as daemon
  src/powerapi/puller/handlers.py
Labels: bug

#324 fix(cli): Fix environment variables parser
  src/powerapi/cli/common_cli_parsing_manager.py
  src/powerapi/cli/config_parser.py
  src/powerapi/cli/generator.py
  src/powerapi/utils/cli.py
  tests/unit/cli/conftest.py
  tests/unit/cli/test_generator.py
  tests/utils/cli/several_inputs_outputs_stream_mode_enabled_configuration.json
Labels: bug
