Repository powerapi-ng/powerapi, pull requests merged in 2025-02, with the labels that each got.

#532 ci: Add `ruff` linter
  .github/workflows/build.yml
  .ruff.toml
  pyproject.toml
Labels: enhancement

#534 ci: Remove `flake8` (superseded by `ruff`)
  .flake8
  .github/workflows/build.yml
  pyproject.toml
Labels: refactoring

#535 ci(build): Always upload coverage reports to Codecov
  .github/workflows/build.yml
Labels: enhancement

#536 refactor: Use PEP-585 type hints for standard collections
  .ruff.toml
  src/powerapi/cli/config_validator.py
  src/powerapi/cli/generator.py
  src/powerapi/database/csvdb.py
  src/powerapi/database/file_db.py
  src/powerapi/database/influxdb2.py
  src/powerapi/database/mongodb.py
  src/powerapi/database/opentsdb.py
  src/powerapi/database/prometheus_db.py
  src/powerapi/database/socket_db.py
  src/powerapi/database/virtiofs_db.py
  src/powerapi/dispatch_rule/dispatch_rule.py
  src/powerapi/dispatch_rule/hwpc_dispatch_rule.py
  src/powerapi/dispatch_rule/power_dispatch_rule.py
  src/powerapi/dispatch_rule/procfs_dispatch_rule.py
  src/powerapi/formula/abstract_cpu_dram_formula.py
  src/powerapi/formula/formula_actor.py
  src/powerapi/processor/pre/k8s/metadata_cache_manager.py
  src/powerapi/processor/pre/k8s/monitor_agent.py
  src/powerapi/report/control_report.py
  src/powerapi/report/formula_report.py
  src/powerapi/report/hwpc_report.py
  src/powerapi/report/power_report.py
  src/powerapi/report/procfs_report.py
  src/powerapi/report/report.py
  tests/unit/processor/conftest.py
  tests/unit/processor/pre/k8s/test_monitor_agent.py
  tests/utils/formula/dummy/dummy_formula_actor.py
  tests/utils/report/hwpc.py
Labels: refactoring

#537 refactor: Use PEP-604 annotations for union types
  .ruff.toml
  src/powerapi/dispatch_rule/dispatch_rule.py
  src/powerapi/processor/pre/k8s/metadata_cache_manager.py
  src/powerapi/processor/pre/k8s/monitor_agent.py
Labels: refactoring

#538 refactor: Remove redundant `open` mode argument
  .ruff.toml
  src/powerapi/cli/config_parser.py
  src/powerapi/database/csvdb.py
  src/powerapi/database/file_db.py
  tests/utils/cli/base_config_parser.py
  tests/utils/report/hwpc.py
Labels: refactoring

#539 refactor: Remove usage of printf string formatting
  .ruff.toml
  src/powerapi/report/control_report.py
  src/powerapi/report/hwpc_report.py
  src/powerapi/report/power_report.py
  src/powerapi/report/procfs_report.py
  src/powerapi/report/report.py
Labels: refactoring

#540 refactor: Replace deprecated `typing` imports with `collections.abc`
  .ruff.toml
  src/powerapi/cli/config_parser.py
  src/powerapi/cli/generator.py
  src/powerapi/cli/parsing_manager.py
  src/powerapi/database/socket_db.py
  src/powerapi/dispatcher/dispatcher_actor.py
  src/powerapi/report/report.py
Labels: refactoring

#541 refactor: Use `unittest.mock` instead of the deprecated `mock` library
  .ruff.toml
  pyproject.toml
  tests/unit/actor/abstract_test_actor.py
  tests/unit/actor/test_supervisor.py
Labels: refactoring

#542 refactor: Remove commented-out code
  .ruff.toml
  src/powerapi/actor/actor.py
  src/powerapi/cli/config_parser.py
  src/powerapi/database/csvdb.py
Labels: refactoring

#544 refactor: Use `is` instead of `==` to compare types
  .ruff.toml
  tests/unit/cli/test_parsing_manager.py
Labels: refactoring

#545 refactor: Format logging messages the same way across the codebase
  .ruff.toml
  src/powerapi/handler/handler.py
  src/powerapi/pusher/handlers.py
Labels: refactoring

#546 refactor: Use `removeprefix` to remove an exact prefix from a string
  .ruff.toml
  tests/unit/puller/test_puller_actor.py
Labels: refactoring

#547 refactor: Concatenate collections with iterable unpacking
  .ruff.toml
  src/powerapi/database/prometheus_db.py
  src/powerapi/dispatch_rule/power_dispatch_rule.py
  src/powerapi/dispatcher/dispatcher_actor.py
  src/powerapi/report/formula_report.py
  src/powerapi/report/hwpc_report.py
  src/powerapi/report/power_report.py
  src/powerapi/report/procfs_report.py
  tests/unit/dispatcher/test_dispatcher_actor.py
Labels: refactoring

#550 refactor: Cleanup asserts in unit tests
  .ruff.toml
  tests/unit/actor/test_supervisor.py
  tests/unit/cli/test_binding_manager.py
  tests/unit/cli/test_config_parser.py
  tests/unit/cli/test_config_validator.py
  tests/unit/cli/test_generator.py
Labels: refactoring

#555 fix(report/hwpc): Raise `BadInputData` exception when csv line is incomplete
  src/powerapi/report/hwpc_report.py
  tests/unit/report/test_hwpc_report.py
Labels: bug

#564 fix(database/opentsdb): Add timezone info to timestamp before sending to OpenTSDB
  src/powerapi/database/opentsdb/opentsdb.py
Labels: bug
